# Generated by Django 4.0.2 on 2022-10-05 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.TextField(max_length=3)),
                ('subject', models.TextField(max_length=4)),
                ('description', models.TextField(max_length=100)),
                ('component', models.TextField(max_length=3)),
                ('topic', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listapi.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField(max_length=10)),
                ('start_time', models.TextField(max_length=21)),
                ('facility_description', models.TextField(max_length=25)),
                ('end_time', models.TextField(max_length=21)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listapi.section')),
            ],
        ),
    ]
