# Generated by Django 4.1.1 on 2022-10-06 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_number', models.IntegerField(unique=True)),
                ('semester_code', models.IntegerField()),
                ('course_section', models.TextField(max_length=3)),
                ('subject', models.TextField(max_length=4)),
                ('catalog_number', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('units', models.TextField(max_length=10)),
                ('component', models.TextField(max_length=3)),
                ('class_capacity', models.IntegerField()),
                ('wait_list', models.IntegerField()),
                ('wait_cap', models.IntegerField()),
                ('enrollment_total', models.IntegerField()),
                ('enrollment_available', models.IntegerField()),
                ('topic', models.TextField(blank=True, null=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listapi.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.TextField(max_length=10)),
                ('start_time', models.TextField(max_length=21)),
                ('facility_description', models.TextField(max_length=50)),
                ('end_time', models.TextField(max_length=21)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listapi.section')),
            ],
        ),
    ]
