# Generated by Django 4.1.1 on 2022-10-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='section',
            name='class_capacity',
            field=models.TextField(max_length=6),
        ),
    ]
