# Generated by Django 4.1.1 on 2022-10-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listapi', '0002_remove_section_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='catalog_number',
            field=models.TextField(max_length=6),
        ),
        migrations.AlterField(
            model_name='section',
            name='class_capacity',
            field=models.IntegerField(),
        ),
    ]
